# Testing Python 3.7 requires using the `xenial` dist which uses
# virtual machines rather than LXC and tends to take longer, so
# use it only where necessary.
# Testing on macOS/darwin always uses virtual machines so only
# test the bare minimum.
matrix:
  include:
  - os: linux
    language: python
    python: "2.7"
    env: TOXENV=py27
  - os: linux
    language: python
    python: "3.4"
    env: TOXENV=py34
  - os: linux
    language: python
    python: "3.5"
    env: TOXENV=py35
  - os: linux
    language: python
    python: "3.6"
    env: TOXENV=py36
  - os: linux
    language: python
    dist: xenial
    python: "3.7"
    env: TOXENV=py37
  - os: osx
    language: generic
    env: TOXENV=py27
  - os: osx
    language: generic
    env: TOXENV=py34
  - os: linux
    language: python
    python: "3.6"
    env: TOXENV=codestyle
    before_install: true

env:
  global:
    - IPFS_VERSION=0.4.21
    - IPFS_SHA512_LINUX=f344969cad4c2a4f81692c5e7e11dafc420694653fa37d1e389b5c458ee88ea34ea22efceb747351bb579247f1c494e47f667e7a178e8197ba4cad43a6e52f87
    - IPFS_SHA512_DARWIN=cbb85560182a6af4187029b24414a217d706c4dd636aa0634061479d103ca9ec9f94b44787d131e9697d1347c6026dd42e70a9185e0917920bbe81f010154051


# Ensure go-IPFS is available for testing
before_install:
  # Make the `sha512sum` available on macOS under that name!
  - export PATH="$(echo /usr/local/Cellar/coreutils/*/libexec/gnubin):${PATH}"
  
  # Figure out parameters based on environment
  - if [ "${TRAVIS_OS_NAME}" != "osx" ]; then export IPFS_PLATFORM="linux-amd64" IPFS_SHA512="${IPFS_SHA512_LINUX}"; else export IPFS_PLATFORM="darwin-amd64" IPFS_SHA512="${IPFS_SHA512_DARWIN}"; fi
  # Download the daemon application
  - wget "https://dist.ipfs.io/go-ipfs/v${IPFS_VERSION}/go-ipfs_v${IPFS_VERSION}_${IPFS_PLATFORM}.tar.gz" -O "/tmp/ipfs.tar.gz"
  # Verify the checksum
  - echo "${IPFS_SHA512}  /tmp/ipfs.tar.gz" | sha512sum -c
  # Extract verify archive
  - tar -xzvf "/tmp/ipfs.tar.gz"
  # Set up path
  - export PATH="${PWD}/go-ipfs:${PATH}"

install:
  # Install Python 3.4.4 (the last release binary version) for Python 3 testing on Darwin
  - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${TOXENV}" = "py34" ]; then wget "https://www.python.org/ftp/python/3.4.4/python-3.4.4-macosx10.6.pkg" -O /tmp/python.pkg; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${TOXENV}" = "py34" ]; then echo "349c61e374f6aeb44ca85481ee14d2f5  /tmp/python.pkg" | md5sum -c; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${TOXENV}" = "py34" ]; then sudo installer -pkg /tmp/python.pkg -target /; fi
  # Just install PIP on the native Python 2.7 stack for Python 2 testing on Darwin
  - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${TOXENV}" = "py27" ]; then sudo easy_install pip; fi
  
  # Install the test runner
  - pip install tox

script: tox